# Project information
site_name: 'AIOT开放平台文档中心'
site_description: 'AIOT开放平台的官方文档，帮助开发基于AIOT平台的物联网应用'
site_author: 'Penny & Forrest'
site_url: 'http://docs.opencloud.aqara.com/'

# Repository
repo_name: 'aqara/opencloud-docs'
repo_url: 'https://github.com/aqara/opencloud-docs/'

# Copyright
copyright: '版权所有 &copy; 2017 - 2019 深圳绿米联创科技有限公司'

# Theme Configuration 
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'zh'
  feature:
    tabs: true

# Customization
extra:
  search: 
    language: 'en'
  disqus: 
  social:
    - type: 'globe'
      link: 'https://opencloud.aqara.com'
    - type: 'github'
      link: 'https://github.com/aqara'
    - type: 'weibo'
      link: 'https://weibo.com/u/5232002130'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'

# Google Analytics
google_analytics:
  - 'UA-116424606-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Contents
pages:
- 新手帮助: 
  - AIOT开放平台介绍: index.md
  - 产品介绍: guideline/product-discription.md
  - 账号与密码: guideline/account-and-password.md
- 开发手册:
  - 云端开发手册: development/cloud-development.md
  - 场景和自动化接口文档: development/automation-api-demo.md
  - 国家（地区码）: development/region_code.md
  - 网关局域网通讯协议: development/gateway-LAN-communication.md
#- 部署与运维:
#  - 安装与配置指南: implementation/installation-and-configuration.md
- 常见问题: 
  - 产品问题: faq/faq-product.md
  - 应用开发: faq/faq-development.md
- 开发者资源: 
  - 设备入网SDK: sdk/sdk-v1.0.md
